title: Rajaa OMARY # your name (or website title) here
logo: "/images/1607035213028.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Full Stack Developer  
  <br><br>
  <a href="https://www.linkedin.com/in/rajaaomary/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
